import argparse
import os
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

def load_data(csv_path):
    """Load the CSV file generated by chess_accuracy_from_pgn.py"""
    df = pd.read_csv(csv_path)
    # Ensure numeric columns are proper types
    numeric_cols = ['Games', 'Avg_Accuracy', 'Std_Accuracy', 'Median_Accuracy', 'MAD_Accuracy']
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    # Elo may be missing or non‑numeric; coerce safely
    df['Elo'] = pd.to_numeric(df['Elo'], errors='coerce')
    return df

def plot_average_accuracy(df, out_dir, base_name):
    """Horizontal bar chart of average accuracy per player, sorted by Elo descending"""
    # Sort by Elo (descending) then by player name
    # For horizontal bar chart, we want the first item at the top, so we sort ascending for plotting
    # (because barh plots from bottom up)
    df_sorted = df.sort_values(by=['Elo', 'Player'], ascending=[True, False])
    
    # Dynamic height based on number of players
    height = max(6, len(df) * 0.3 + 2)
    plt.figure(figsize=(10, height))
    
    plt.barh(df_sorted['Player'], df_sorted['Avg_Accuracy'], color='steelblue')
    plt.xlabel('Average Accuracy (%)')
    plt.title('Average Accuracy per Player (Sorted by Elo)')
    
    # Zoom in on the relevant range
    min_acc = df_sorted['Avg_Accuracy'].min()
    if pd.notna(min_acc):
        plt.xlim(max(0, min_acc - 2), 100.5)
        
    plt.grid(axis='x', linestyle='--', alpha=0.5)
    plt.tight_layout()
    
    out_path = os.path.join(out_dir, f"{base_name}_avg_accuracy.png")
    plt.savefig(out_path, dpi=150)
    plt.close()
    print(f"Saved average accuracy bar chart to {out_path}")

def plot_accuracy_histogram(df, out_dir, base_name):
    """Histogram of all players' average accuracies"""
    plt.figure(figsize=(8, 5))
    plt.hist(df['Avg_Accuracy'].dropna(), bins=20, color='seagreen', edgecolor='black')
    plt.xlabel('Average Accuracy (%)')
    plt.ylabel('Number of Players')
    plt.title('Distribution of Player Average Accuracies')
    
    # Force integer ticks on Y-axis
    plt.gca().yaxis.set_major_locator(MaxNLocator(integer=True))
    
    plt.tight_layout()
    out_path = os.path.join(out_dir, f"{base_name}_accuracy_histogram.png")
    plt.savefig(out_path, dpi=150)
    plt.close()
    print(f"Saved accuracy histogram to {out_path}")

def plot_elo_vs_accuracy(df, out_dir, base_name):
    """Scatter plot of Elo vs average accuracy"""
    # Filter out rows with missing Elo or Accuracy
    df_clean = df.dropna(subset=['Elo', 'Avg_Accuracy'])
    
    if df_clean.empty:
        print("Warning: No valid Elo data found for scatter plot. Skipping.")
        return

    plt.figure(figsize=(8, 5))
    plt.scatter(df_clean['Elo'], df_clean['Avg_Accuracy'], c='darkorange', alpha=0.7)
    plt.xlabel('Elo')
    plt.ylabel('Average Accuracy (%)')
    plt.title('Elo vs Average Accuracy')
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.tight_layout()
    
    out_path = os.path.join(out_dir, f"{base_name}_elo_scatter.png")
    plt.savefig(out_path, dpi=150)
    plt.close()
    print(f"Saved Elo vs Accuracy scatter plot to {out_path}")

def main():
    parser = argparse.ArgumentParser(description='Visualize chess accuracy CSV data')
    parser.add_argument('csv_file', help='Path to the CSV file produced by chess_accuracy_from_pgn.py')
    parser.add_argument('-o', '--output_dir', default=None, help='Directory to store generated plots (default: same as CSV)')
    args = parser.parse_args()

    csv_path = args.csv_file
    if not os.path.isfile(csv_path):
        print(f"Error: CSV file not found: {csv_path}")
        return

    out_dir = args.output_dir or os.path.dirname(csv_path)
    os.makedirs(out_dir, exist_ok=True)
    base_name = os.path.splitext(os.path.basename(csv_path))[0]

    df = load_data(csv_path)
    if df.empty:
        print("No data to plot.")
        return

    plot_average_accuracy(df, out_dir, base_name)
    plot_accuracy_histogram(df, out_dir, base_name)
    plot_elo_vs_accuracy(df, out_dir, base_name)

if __name__ == '__main__':
    main()
